
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  labels:
    app: dragonfly
  name: dragonfly
spec:
  replicas: 2
  resources:
    requests:
      cpu: 1
      memory: 500Mi
    limits:
      cpu: 1
      memory: 500Mi
  serviceSpec:
    type: LoadBalancer
    annotations:
      cloud.google.com/load-balancer-type: "internal"

